language: go

dist: xenial

go:
  - "1.11"
  - "1.x"
  - "master"

matrix:
  allow_failures:
    - go: "master"
  fast_finish: true

script: go test -v

env:
- GO111MODULE=on

cache:
  directories:
    - /home/travis/gopath/pkg/mod

install: true  # skip, handled by "cache" stage

stages:
  - cache
  - test
  - deploy

jobs:
  include:
    - stage: cache
      script: go mod download
    - stage: deploy
      script: skip
      env:
        - secure: "FOx2FP9HJs1AupPp2yZ84z5yaPwYSRAaT2OGoRf/RAgRtzxF0qZdi9T/IBu5Kz5b1IyMWvteIjEj2PFyKjRTkn9mASzPnk0+ymtfxdxm34TM0gXfy/3WgG4W90bNeiX3ZQ8cXliwBvBIe7HYfRz9733Q1Mh2P2NVhtWi/PlPelDbvtvTVnEArrveXln/HbnDhjVN3MdPc4eCZymQT4QtcuQ89ERdFqVGaOYGevMAYaaGJ2BgsT8I41YDCs+TkuLA3cbZmDp4Q2DvRoLrPW2MJh6fwmql+3pButDvehNE+I4OL+R1d7kWEhY9ikzvsp0x5dxyEf2PBBDv2A2z8cGb0MfQFhPvwtlc5drDrv9psqGrNjBZZ38pGWJas3kMr6yGMj1au7CaVvW16W+23XFRSuwE0s4V4ls1z5a5nUTi7Yfgi1NtJiFQq3iiSRcB1SkH/FV0UKM3Gy/grQEUywR+V0p8hO8C7QD+dFRQwg822xraCaN3oLNND5EUmA6bI9knAWZTjFMXwYfiO2W3cdWoQ3YtLlULPzNBqVAjOGgkvtnZclLyAK8iq4ygnXo+VIIOZ4EK0Ze9ibsDZHwbuX06vIoG/wbAFN9HV+WwaPE1pzfcjJ9wkhERz6OPIZlA59DRDqHSpIA45kf38VEBRTA47LT5z2ThAAbuWFWTIkBOn38="
      before_install:
      deploy:
        provider: script
        script: 'curl -si -H "Content-Type: application/json" --data "{\"source_type\": \"Tag\", \"source_name\": \"${TRAVIS_TAG}\"}" -X POST https://registry.hub.docker.com/u/costela/docker-etchosts/trigger/${DOCKER_HUB_TOKEN}/'
        on:
          tags: true
